### ISSUE TITLE
Quickstart docs -> does not work on Fedora23 due to conflict in python deps

### ISSUE THREAD

**Issue by queria** [rhosqeauto/InfraRed#199]
When following [quickstart](http://infrared.readthedocs.io/en/devel/quickstart.html) steps,
it ends in unusable ir-* commands:
```
$ git clone https://github.com/rhosqeauto/InfraRed.git ir
$ cd ir
$ pip install --user -e .
$ ir-provisioner --help
Traceback (most recent call last):
  File "/home/psedlak/.local/bin/ir-provisioner", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-keystoneclient 1.3.0 (/usr/lib/python2.7/site-packages), Requirement.parse('python-keystoneclient!=1.8.0,!=2.1.0,>=1.6.0'), set(['python-troveclient', 'python-glanceclient', 'python-cinderclient']))
```

almost complete [log from `pip install --user -e .`](http://dpaste.com/2SZ2K4X)
and then [output of `pip freeze`](http://dpaste.com/03JNF8G)

**Comment by queria** [comment]
almost complete [log from `pip install --user -e .`](http://dpaste.com/2SZ2K4X) of the 
and then [output of `pip freeze`](http://dpaste.com/03JNF8G)

**Comment by queria** [comment]
also, there is mentioned in the docs 'pip install .' which just cannot work - would require sudo which is just the worst practice (in case when distro provides python packages /like in rpm etc)

so virtualenv definitely should be used here, esp. when there seems to be quite a bunch of pkgs needed in newer version that what even current/latest fedora provides

**Comment by queria** [comment]
and now i've also noticed it did reinstalled ansible to newer version, breaking other stuff (like khaleesi) for me, oh *$%&!

**Comment by obaranov** [comment]
you definitely need to use virtualenv to avoid version conflicts and ansible reinstallation.  I think we need to update documentation saying that *recommended* way for infrared is to use vertualenv.

**Comment by yfried-redhat** [comment]
@queria Could you please update the doc to say "use virtualenv"?

**Comment by fhubik** [comment]
Already on it, WIP https://review.gerrithub.io/#/c/278639/.
