### ISSUE TITLE
Support for additional ansible parameters

### ISSUE THREAD

**Issue by fhubik** [rhosqeauto/InfraRed#204]
It would be nice if there were some ability to pass ansible parameters to ir-XYZ commands (something like --inventory or -e is done now), so all of ansible params would be inherited (and accessible from) to IR level.

So far I couldn't figure out how to do it. Proposal example:
`ir-installer --inventory hosts ospd --product-core-version=8 ... --start-at-task=ABC`

**Comment by yfried-redhat** [comment]
IR is meant wrap Ansible inexperience users. As such we expose only what is required for general use cases.
Advanced features (such as `step`, `start-at-task`, etc...) can be easily used by:
```
$ ir-installer ospd [...] -o MY_SETTINGS.yml --dry-run
$ ansible-playbook -i hosts -e @MY_SETTINGS.yml playbooks/install.yml --start-at-task=ABC
```
