### ISSUE TITLE
overcloud VMs should use the same naming as the they get deployed by the ospd installer

### ISSUE THREAD

**Issue by mcornea** [rhosqeauto/InfraRed#229]
Currently Infrared creates the VMs with an index starting at 1 if there are multiple nodes of the same type. For instance:

Id    Name                           State
---------------------------------------------------
17    undercloud                   running
25    controller1                    running
28    compute                       running
29    controller2                    running
30    controller3                    running

The installer deploys the nodes by always having an index starting at 0:

+-------------------------+-
| Name                        | 
+-------------------------+-
| overcloud-compute-0     | 
| overcloud-controller-0  | 
| overcloud-controller-1  | 
| overcloud-controller-2  | 
+-------------------------+-

It would be great to have Infrared create the VMs used for overcloud nodes with the same naming - always use an index starting at 0, e.g:

 Id    Name                           State
---------------------------------------------------
17    undercloud                   running
25    controller-0                    running
28    compute-0                       running
29    controller-1                    running
30    controller-2                    running

**Comment by yfried-redhat** [comment]
The 0 based issue was fixed.
I think this is addressed by RHOSINFRA-194.
If not, please open a JIRA item or comment there
