### ISSUE TITLE
SSL parameter does not look to be used resulting in SSL not to be deployed

### ISSUE THREAD

**Issue by krcmarik** [rhosqeauto/InfraRed#237]
Hi,

I am trying to add some new features into InfraRed so I am poking around the code to get some understanding of the structure. I am looking at master branch and It really seems like some features are not being deployed even though specified with using parameters of ir-installer.

For example SSL, I can see --overcloud-ssl parameter in spec but I cannot see it anywhere used, I can see some roles created for SSL feature but I cannot see these roles to be included/called in any playbook. 

If I do git grep:
$ git grep -i ssl
LICENSE:  You may not propagate or modify a covered work except as expressly
library/beaker_provisioner.py:        # whether verify the SSL certificate or not
library/beaker_provisioner.py:        import ssl
library/beaker_provisioner.py:        ssl_context = ssl.create_default_context(cafile=self.ca_cert)
library/beaker_provisioner.py:        transport = xmlrpclib.SafeTransport(context=ssl_context)
roles/installer/ospd/overcloud/ssl/tasks/main.yml:- name: create the self signed SSL
roles/installer/ospd/overcloud/ssl/tasks/main.yml:  shell: "openssl genrsa -out {{ installer.overcloud.template_base }}/overcloud-privkey.pem 2048"
roles/installer/ospd/overcloud/ssl/tasks/main.yml:  shell: "openssl req -new -x509 -key {{ installer.overcloud.template_base }}/overcloud-privkey.pem -out {{ installer.overcloud.template_base }}/overcloud-cacert.pem -days 365 -subj '/C=US/ST=NC/L=Raleigh/O=Red HAt/OU=QE/CN={{ installer.network.isolation.template.content.parameter_defaults.ExternalAllocationPools[0].start }}'"
roles/installer/ospd/overcloud/ssl/tasks/main.yml:      - {dest: "{{ installer.overcloud.template_base }}/enable-tls.yaml", regex: "(SSLCertificate:.*\\s+)The contents of your certificate.*$", replace_with: "\\1{{ cacert.stdout | indent(4) | string }}"}
roles/installer/ospd/overcloud/ssl/tasks/main.yml:      - {dest: "{{ installer.overcloud.template_base }}/enable-tls.yaml", regex: "(SSLKey:.*\\s+)The contents of the private key.*$", replace_with: "\\1{{ private_key.stdout | indent(4) | string }}"}
roles/installer/ospd/overcloud/ssl/tasks/main.yml:      - {dest: "{{ installer.overcloud.template_base }}/inject-trust-anchor.yaml", regex: "(SSLRootCertificate:.*\\s+)The contents of your root CA.*$", replace_with: "\\1{{ cacert.stdout | indent(4) | string }}"}
settings/installer/ospd/ospd.spec:                overcloud-ssl:
settings/installer/ospd/ospd.spec:                    help: Specifies whether ths SSL should be used for overcloud
settings/tester/tempest/setup/git.yml:    - openssl-devel

I can see the role, I can see the parameter defined in spec but I dont really understand where It is used, no playbook has the role.

**Comment by fhubik** [comment]
It looks like this support was removed in commit https://github.com/rhosqeauto/InfraRed/pull/136/commits/e248f13a6f4723d5927268df3710e9c020a47882, can we verify/disprove this issue?

**Comment by tkammer** [comment]
@krcmarik Indeed, it appears I messed up with the major refactor I've done and accidentally removed the SSL invocation.
Thanks for pointing this out!
We will add it again shortly.

**Comment by yfried-redhat** [comment]
Closed by 647808786b165bfe5a03f9b1287cdb9fc896b008
