### ISSUE TITLE
[question] virt-manager and friends installed on the virthost

### ISSUE THREAD

**Issue by mcornea** [rhosqeauto/InfraRed#238]
Hi everyone,

Is there a reason why we install virt-manager, virt-viewer, xorg-x11-apps and xauth on the virthost? 
https://github.com/rhosqeauto/InfraRed/blob/stable/settings/provisioner/virsh/virsh.yml#L23-L25

IMO we can access the virthost remotely with virt-manager installed locally on your laptop or by SSH tunnelling  to the VNC ports if needed. We can save some time on the deployment if we skip installing these packages on the virthost. 

Thanks!

**Comment by yfried-redhat** [comment]
Opened JIRA RHOSINFRA-200
