### ISSUE TITLE
Missing breakpoints

### ISSUE THREAD

**Issue by mcornea** [rhosqeauto/InfraRed#243]
With the previous stable version we had the option to stop the deployment at various breakpoints during the deployment process. It looks like we don't have this option anymore. Can we add this functionality back? Thanks!

**Comment by yfried-redhat** [comment]
@mcornea,
Hi, this was removed in a refactor. Will be back after Baremetal is merged.
I will close this ticket and open a JIRA about it

**Comment by yfried-redhat** [comment]
Opened ticket RHOSINFRA-199
