### ISSUE TITLE
cloud.yml not mentioned in the docs

### ISSUE THREAD

**Issue by queria** [rhosqeauto/InfraRed#263]
Couldn't find any info in the docs about providing 'cloud' info for ir-provisioner openstack(...).

I would expect it mentioned in "run" section at least, maybe even setup?
Describing how it should look like, some example + link to os-client-config for more.

**Comment by fhubik** [comment]
WIP - https://review.gerrithub.io/#/c/278639/.

**Comment by fhubik** [comment]
fix: #263
