### ISSUE TITLE
README.rst and Documentation Improvement

### ISSUE THREAD

**Issue by yazug** [rhosqeauto/InfraRed#264]
Missing the Basics for some documentation.

Could use in the README a quick description of What is this project and Why would I use it.

Aslo the documentation is missing this at the front page as well.

**Comment by yazug** [comment]
Something to the effect of InfraRed allows you to provision and install OpenStack using provided tools

**Comment by fhubik** [comment]
WIP - https://review.gerrithub.io/#/c/278639/.

**Comment by yazug** [comment]
https://review.gerrithub.io/#/c/280852
