### ISSUE TITLE
Cleanup excess of branches

### ISSUE THREAD

**Issue by yazug** [rhosqeauto/InfraRed#265]
There appears to be a number of dead branches in the main repo, if this is intended to be the master repo, let's try to keep the branches present clean and well defined

  remotes/origin/bad-pr
  remotes/origin/bad-pr-2
  remotes/origin/devel
  remotes/origin/installer-devel
  remotes/origin/master
  remotes/origin/revert-189-devel
  remotes/origin/stable
  remotes/origin/stable-candidate
  remotes/origin/stable-v0.0.1
  remotes/origin/testgerrit
  remotes/origin/testing

of these stable and master look to be the only branches with activity

If they have stuff of interest to one person, can the branch be moved out to a personal fork/clone of this repo instead of the main repo.  this way when someone clones/forks the main repo for contributions they are not burdened with a bunch of useless branches.

**Comment by yfried-redhat** [comment]
Done. only stable and master left.
