### ISSUE TITLE
Optional gate for ospd/packstack for gerrit patches

### ISSUE THREAD

**Issue by obaranov** [rhosqeauto/InfraRed#268]
Currently we have gates only for provisioners. 
It would be great to have an option to trigger ospd or packstack (installer) jobs from the gerrit patches. By default these gate won't run to save time for us, But if user wants to test changes on installer he can just type "test ospd" or 'test packstack" and this will trigger additional gates.

**Comment by yfried-redhat** [comment]
I'm actually ok with any reasonable variant gate that is triggered only on-demand.
We could go a little further and trigger gates based on a white/black list of files changed in a patch.
Something like

- convert openstack to openstack+packstack and run on any change to cli/openstack/library/packstack
- run ospd gate on any change to cli/virsh/ospd
- add tempest sanity gates on demand
- add LB/scale/etc tests on demand

I know @queria and @fhubik already discussed this.

I'm closing this ticket. please create a JIRA issue so we can work on it in CI repo
