### ISSUE TITLE
rhosp-director-images doesn't exist for 7.0

### ISSUE THREAD

**Issue by iranzo** [rhosqeauto/InfraRed#271]
The file at https://github.com/rhosqeauto/InfraRed/blob/master/roles/installer/ospd/images/tasks/rpm.yml

Assumes that there's always an rpm package for rhosp-director-images, but for OSP7 it doesn't.

Should the package be declared for versions 8 or higher and if not, make user to download it from CDN?

**Comment by iranzo** [comment]
Downloading them manually and symlinking fixed this issue for the deployment:

[root@undercloud-0 rhosp-director-images]# pwd
/usr/share/rhosp-director-images
[root@undercloud-0 rhosp-director-images]# ls -l
total 1267692
-rw-r--r--. 1 root root   61419520 Oct  7  2015 deploy-ramdisk-ironic-7.3.1-39.tar
lrwxrwxrwx. 1 root root         34 Sep 29 09:41 deploy-ramdisk-ironic.tar -> deploy-ramdisk-ironic-7.3.1-39.tar
-rw-r--r--. 1 root root  159324160 Mar 17  2016 discovery-ramdisk-7.3.2-59.tar
lrwxrwxrwx. 1 root root         30 Sep 29 09:41 discovery-ramdisk.tar -> discovery-ramdisk-7.3.2-59.tar
-rw-r--r--. 1 root root 1077370880 Jun  3 12:02 overcloud-full-7.3.2-60.tar
lrwxrwxrwx. 1 root root         27 Sep 29 09:30 overcloud-full.tar -> overcloud-full-7.3.2-60.tar

**Comment by fhubik** [comment]
Hi Pablo,
like you said, rpm is avaiable only for OSPd>=8. For 7 with InfraRed you need to use
"--images-task=import --images-url=<link_where_you_downloaded_7_images>"
instead of
"--images-task=rpm".

Filip

**Comment by iranzo** [comment]
Thanks Filip, will take a  note about it!
