### ISSUE TITLE
fatal: [undercloud-0]: FAILED! => {"changed": false, "failed": true, "msg": AnsibleUndefinedVariable: 'dict object' has no attribute 'facter_ipaddress_management'"}

### ISSUE THREAD

**Issue by iranzo** [rhosqeauto/InfraRed#272]
The requirements should also install `facter` on the virtualization host if not the error:

~~~
fatal: [undercloud-0]: FAILED! => {"changed": false, "failed": true, "msg": AnsibleUndefinedVariable: 'dict object' has no attribute 'facter_ipaddress_management'"}
~~~

is raised during deployment.

**Comment by yfried-redhat** [comment]
Hi @iranzo 
This is probably because you don't have "facter" on your hypervisor. It's a prerequisite that we are currently working on removing.

Also, we no longer work with github issues. please use rhos-infrared@redhat.com mailing list for questions, or the JIRA board for bugs.

Regards
Yair
