### ISSUE TITLE
[Setup data interface] task fails

### ISSUE THREAD

**Issue by bregman-arie** [rhosqeauto/InfraRed#274]
Recently our builds started to fail with the following error (using InfraRed stable):

16:55:55 TASK [Setup data interface] ****************************************************
16:55:55                      [[ previous task time: 0:00:10.699610 = 10.70s / 67.34s ]]
16:55:55 <10.8.181.212> ESTABLISH SSH CONNECTION FOR USER: cloud-user
16:55:55 <10.8.181.212> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/rhos-ci/.ssh/rhos-jenkins/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=30 -o ControlPath=/home/rhos-ci/.ansible/cp/%h-%r 10.8.181.212 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478192155.45-260534632336209 `" && echo ansible-tmp-1478192155.45-260534632336209="` echo $HOME/.ansible/tmp/ansible-tmp-1478192155.45-260534632336209 `" ) && sleep 0'"'"''
16:55:56 fatal: [neutron-1173-1478192075-dsvm-functional-tester-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

**Comment by yfried-redhat** [comment]
Could you please provide some more data?

**Comment by bregman-arie** [comment]
Which data?

Anyway, I think it might be issue with the lab, as I don't see those anymore. Closing the issue.
