### ISSUE TITLE
Split "DEBUG" from "-vvvv"

### ISSUE THREAD

**Issue by tkammer** [rhosqeauto/InfraRed#29]
There are two different flags here.
DEBUG, this is a feature for someone to check what the ir-provison does (should be a flag "--debug")
VERBOSE, this is ansible -v option, this should be a separate flag to let the user choose verbosity of the output.
Please break the ir-provision DEBUG showing the merge of all files to a --debug flag.
Please break the ir-provision VERBOSE showing ansible verbosity to a --verbose (no flag means -v, flag means -vvvv)

**Comment by aopincar** [comment]
@tkammer , IMHO there is no need to split the 'debug' from the verbosity.
The all point is to work with one tool, hence, the verbosity level of ir-provision & ansible-playbook should be the same. Besides that, ansible-playbook has no special 'debug' flag, only verbose flag which uses also for debugging when running in full verbose level (-vvvv).

**Comment by gamado** [comment]
retest
