### ISSUE TITLE
Add the ability to point to a different root dir which includes all the relevant dir

### ISSUE THREAD

**Issue by aopincar** [rhosqeauto/InfraRed#32]
A user should has the ability to point the root dir (InfraRed) to a differnent dir which includes all needed dirs (settings, playbooks, library etc...)
In this case, instead of changing the paths of all dir in the the infrared.cfg file, there'll be a need to change only the path to the root dir, and the other paths will point into it automatically

**Comment by yfried-redhat** [comment]
This is can be done either via cfg or multi-settings
