### ISSUE TITLE
fix the reference of "ir-install" and "ir-test" from provisioner to correspond name

### ISSUE THREAD

**Issue by tkammer** [rhosqeauto/InfraRed#40]
The current "ir-install" and "ir-test" are both pointing to the same entry point as "ir-provision".
We should fix this to the installer folder and tester folder.

**Comment by yfried-redhat** [comment]
- `ir-test` was removed.
- `ir-provision` and `ir-install` now point to `provision.py` and `install.py` respectively

Closed by #56
