### ISSUE TITLE
Can 'SpecManager' class be an Abstract class?

### ISSUE THREAD

**Issue by aopincar** [rhosqeauto/InfraRed#46]
The all idea of this class is to create and return parsers which based on spec files - there is no a real need to create and instance of this class for that. Only need to call the 'get_specs' methos with the relevant module name.

**Comment by tkammer** [comment]
To summarize what Ariel is writing here, please make the class a 'Factory' class.

**Comment by obaranov** [comment]
Agree. I will implement that.

**Comment by yfried-redhat** [comment]
Closed by #71
