### ISSUE TITLE
Add IRApplication class and encapsulate main logic there

### ISSUE THREAD

**Issue by obaranov** [rhosqeauto/InfraRed#58]
I'd like to add Application class to encapsulate common IR-<name> logic there. This class will have a major method 'run' which will do the following: 
```
 args, settings_files = self.configure()
 settings = self.lookup(settings_files)
 self.dump_settings(settings)
 self.execute(settings)
```

After that we will be able to create main methods for our ir-<name> app's with some thing like that

```
main_provision = IRApplication.create_for('provisioner', CONF).run
main_installer = IRApplication.create_for('installer', CONF).run
main_tester = IRApplication.create_for('tester', CONF).run
```
What do you think on that? Any ideas?

**Comment by tkammer** [comment]
+1
I'd just change the name to "IRFactory" and use ".create" (no need '_for'), so end result:
provisioner = IRFactory.create('provisioner', CONF)
installer = IRFactory.create('installer', CONF)
tester = IRFactory.create('tester', CONF)

**Comment by aopincar** [comment]
+1 from me also.
This is how it should be done!
This way, the all three entry points will point to the same main method.
